# Generated by Django 5.2.6 on 2026-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavenapp', '0003_cart_order_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
    ]
